Repository aioutecism/amVim-for-VSCode, pull requests merged in 2018-05, with the labels that each got.

#199 Added: `:` to start Command Palette Support
  src/Actions/Command.ts
  src/Actions/CommandLine/CommandLine.ts
  src/Actions/CommandLine/Commands/Base.ts
  src/Actions/CommandLine/Commands/GoToLine.ts
  src/Actions/CommandLine/Commands/NewFile.ts
  src/Actions/CommandLine/Commands/Quit.ts
  src/Actions/CommandLine/Commands/QuitAll.ts
  src/Actions/CommandLine/Commands/VerticalNewFile.ts
  src/Actions/CommandLine/Commands/VisualSplit.ts
  src/Actions/CommandLine/Commands/Write.ts
  src/Actions/CommandLine/Commands/WriteAll.ts
  src/Actions/CommandLine/Commands/WriteQuit.ts
  src/Actions/CommandLine/Commands/WriteQuitAll.ts
  src/Actions/CommandLine/Parser.ts
  src/Modes/Normal.ts
Labels: enhancement

#200 Supports {N} d {motion}
  src/Modes/Normal.ts
  test/ModeNormal/d {N} {motion}.test.ts
  test/ModeNormal/{N} d {motion}.test.ts
Labels: enhancement

#205 (chore) added clean npm script
  package.json
Labels: workflow

#206 Feature/n x and n X
  src/Actions/Delete.ts
  src/Modes/Normal.ts
  test/ModeNormal/{N} x.test.ts
Labels: feature
